---
output: html_document
bibliography: EdLifeHistory1.bib
---


The evolution of pelagic anthozoan larva that parasitize geletatinous zooplankton may also influence the carbon flow within marine food webs in ways that are currently unrecognized or poorly understood.  The contribution of larval anthozoan parasites of medusa to pelagic food chains was suggested over a century ago, in 1887 by N.C. McIntosh [@McIntosh:1887wt], who speculated that they might increase the food suplies for the pelagic juveniles of fish species.  McIntosh was familiar with the contribution of benthic or epifaunal sea anemones within the food chain for common piscine species, and specifically noted a benthic Edwardsiid anemone, commenting that "the stomachs of flounder are frequently distended with *Edwardsia*" [@McIntosh:1887wt].  If larval sea anemones become components of nektonic food chains via their parasitic association with pelagic medusa and ctenophores, they could be contributing to the carbon flow in marine food webs to a greater extent than is widely appreciated.  

Based on gut contents of the butterfish, *Peprilus triacanthus*, that resembled *E. lineata* larva in 1973 [@OVIATT1973361], Oviat *et al.* further examined the potential link between parasitic *E. lineata* and butterfish diet, reporting that 100% (n=45) of *P. triacanthus* caught in early September contained *E. lineata* parasites within their gut contents [@Oviatt:1977jq].  Oviat *et al* also observed butterfish selectively excising and eating *E. lineata* parasites from *M. leidyi* [@Oviatt:1977jq].  Since ctenophores contribute to the diet of numerous fish and sea turtles, it is possible that *E. lineata* parasites constitute a portion of the diet of a far broader set of species than is currently known. To facilitate exploration of *E. lineata's* contribution to the Western Atlantic food web, we have created an interactive food web network within the EdwardsiellaBase shiny web application that displays known predation links where *E. lineata* is consumed in the parasitic form.  The interactive visualization of food webs above is based on a force-directed network graph. Nodes represent species, with edges depicted the direction of predation. Users can interact with the network diagram by clicking and pulling on the nodes to alter the topography of the network. Hover-over by user mouse input initiates a pop-up display of the taxon name. 

-------